---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    jenkins_hostname: localhost


  roles:
    - role: geerlingguy.java
      __java_packages:
        - openjdk-8-jdk
    - name: ansible-jenkins-pipeline
      jenkins_admin_password: admin
      jenkins_git_user: MartinGrue
      jenkins_git_host: https://github.com
      jenkins_git_path: MartinGrue
      jenkins_git_repositories:
      - CICD_Playground