version: "2"
services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    image: ansible
    container_name: ansible
    volumes:
      - ../ansible:/work/ansible
    ports:
      - 7070:8080
    # command: ["ansible-playbook", "ansible/jenkins2.yml"]
    stdin_open: true # docker run -i
    tty: true # docker run -t
